version: '3'

services:
  influxdb:
    image: influxdb
    volumes:
      - $PWD/influxdb:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_DB=jenkins
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  jenkins:
    image: jenkins
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
  grafana:
    image: grafana/grafana
    volumes:
      - $PWD/data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=admin
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=jenkins
      - INFLUXDB_USER=admin
      - INFLUXDB_PASS=admin
    depends_on:
      - influxdb